function pContract  = backtrackingContraction( mapLoad, pSource, pFailed )
%
% function name:            backtrackingContraction
% function objective:       compute the contact point based on the failed extension from pSource to pFailed
% function input:
%   mapLoad:                map matrix
%   pSource:                the point with fialed extension 
%   pFailed:                the point failed to be generated by pSource
% function output:
%   pContact:               the contact point   
%

step                = 0.05;
value               = 0;
angle               = atan2( pSource(2)-pFailed(2), pSource(1)-pFailed(1) );

flag                = false;
while ( ~flag )
    
    pCurPose        = pFailed + value * [ cos(angle), sin(angle) ];
    if ( checkPoint(mapLoad, ceil(pCurPose)) && checkPoint(mapLoad, floor(pCurPose)) && checkPoint(mapLoad, [ceil(pCurPose(1)), floor(pCurPose(2))]) &&...
            checkPoint(mapLoad, [floor(pCurPose(1)), ceil(pCurPose(2))]) )
        flag        = true;
        pContract   = pCurPose;
    else
        value       = value + step;
    end
    
end




end





